Repository Maia-Cochran/habitual, pull requests merged in 2022-09, with the labels that each got.

#1 Maia/setup
  App.js
  components/BottomNavBar.js
  components/CalendarModal.js
  components/Carousel.js
  components/CheckListModal.js
  components/GoodVibeModal.js
  components/GreetingButton.js
  components/Header.js
  components/Home.js
Labels: enhancement, styling, UI/UX

#22 add bottomNavBar
  App.js
  components/BottomNavBar.js
  components/Carousel/styles.js
  components/GreetingButton.js
  components/Header.js
  components/Home.js
  data.js
Labels: help wanted, high-priority, UI/UX, Navigation, MVP

#23 Cg/nav bar
  App.js
  components/BottomNavBar.js
  components/Carousel/styles.js
  components/Home.js
  components/Navigation/CalendarModal.js
  components/Navigation/CheckListModal.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
  package.json
Labels: enhancement, styling, high-priority, UI/UX, Navigation

#24 Mc/feature/build modal template
  .vscode/settings.json
  App.js
  assets/background-with-leaves.png
  components/Header.js
  components/Home.js
  components/ModalTemplate.js
  package-lock.json
  package.json
Labels: question, UI/UX, Modal

#25 So/feature/carousel tiles
  App.js
  components/BottomNavBar.js
  components/Carousel/Carousel.js
  components/Carousel/CarouselItem.js
  components/Carousel/CustomSlider.js
  components/Carousel/data.js
  components/Carousel/styles.js
  components/ModalTemplate.js
  components/Navigation/CalendarModal.js
  components/Navigation/CheckListModal.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
Labels: styling, UI/UX, Navigation, Modal

#27 Feat: fetch api
  components/Carousel/Carousel.js
  components/Carousel/CarouselItem.js
  components/Carousel/GoodVibeView.js
  components/GreetingButton.js
  components/mantraInterval.js
  index.js
Labels: enhancement, question, Data, fetch api

#28 Feat: move data to home screen
  components/Carousel/GoodVibeView.js
  components/GreetingButton.js
  components/Home.js
Labels: Data

#29 Feat: display quote to home screen
  components/GreetingButton.js
  components/Home.js
  components/mantraInterval.js
Labels: enhancement, styling, UI/UX, Data, fetch api

#30 add modal to carousel card
  components/Carousel/Carousel.js
  components/CarouselCards/GoodVibeCard.js
  components/Home.js
Labels: styling, UI/UX, Navigation, Modal

#31 align card and button
  components/Carousel/Carousel.js
  components/Carousel/CustomSlider.js
  components/Carousel/GoodVibeView.js
  components/Carousel/data.js
  components/Carousel/styles.js
  components/CarouselCards/CalendarCard.js
  components/CarouselCards/GoodVibeCard.js
  components/ModalTemplate.js
Labels: enhancement, styling, UI/UX

#32 fixed bug in triggering modal from card
  components/BottomNavBar.js
  components/Carousel/Carousel.js
  components/CarouselCards/GoodVibeCard.js
  components/GreetingButton.js
  components/Header.js
  components/ModalTemplate.js
Labels: bug

#33 combined modal to carousel card
  App.js
  components/CarouselCards/CalendarCard.js
  components/CarouselCards/CheckListCard.js
  components/CarouselCards/FavoritesCard.js
  components/CarouselCards/GoodVibeCard.js
  components/Navigation/CalendarModal.js
  components/Navigation/CheckListModal.js
  components/Navigation/FavoritesModal.js
  components/Navigation/GoodVibeModal.js
Labels: styling, UI/UX, Navigation

#34 Feat: add background image to home screen
  App.js
  components/Home.js
Labels: enhancement, styling, UI/UX, MVP

#35 Mc/feature/connect compliments api to modal
  components/Carousel/Carousel.js
  components/CarouselCards/GoodVibeCard.js
  components/Home.js
  components/ModalTemplate.js
  components/Navigation/GoodVibeModal.js
Labels: bug, fetch api, Modal

#36 Cg/wip home carousel
  components/Carousel/Carousel.js
  components/CarouselCards/CheckListCard.js
  components/GreetingButton.js
  components/Home.js
Labels: help wanted, high-priority

#37 added refresh for goodvibecard and initial load of green card
  App.js
  components/Carousel/Carousel.js
  components/CarouselCards/GoodVibeCard.js
  components/Home.js
  components/Navigation/GoodVibeModal.js
Labels: bug, enhancement, fetch api, Modal

#38 Cg/wip home carousel
  components/Carousel/Carousel.js
  components/Home.js
Labels: enhancement, styling, UI/UX, Data

#39 Feat: import indieflower font to components
  App.js
  components/CarouselCards/CheckListCard.js
  components/CarouselCards/GoodVibeCard.js
  components/GreetingButton.js
  components/Header.js
  components/Home.js
  components/IndieFlowerFont.js
  components/Navigation/CheckListModal.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
  package.json
Labels: enhancement, styling, UI/UX

#43 Cg/format gradient
  components/Navigation/GoodVibeModal.js
  package-lock.json
  package.json
Labels: question, styling, UI/UX

#44 Cg/heart png
  assets/heart.png
  components/Navigation/CheckListModal.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
  package.json
Labels: styling, UI/UX, MVP

#45 So/feature/refresh carousel
  App.js
  assets/NavBarIcons/checklistIcon.png
  assets/NavBarIcons/favoriteIcon.png
  assets/NavBarIcons/lotusIcon.png
  assets/calendar.png
  assets/checkList.png
  assets/favorite.png
  assets/lotus.png
  assets/zen.png
  components/BottomNavBar.js
  components/Carousel/Carousel.js
  components/Carousel/CarouselItem.js
  components/Carousel/CustomSlider.js
  components/Carousel/styles.js
  components/CarouselCards/CalendarCard.js
  components/CarouselCards/CheckListCard.js
  components/CarouselCards/GoodVibeCard.js
  components/Home.js
  components/IndieFlowerFont.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
  utilities/data.js
  utilities/mantra-data.js
Labels: styling, UI/UX, Navigation, Modal

#50 Feat: add updated images
  assets/active-calendar-icon-8.png
  assets/active-checklist-icon-8.png
  assets/active-fav-icon-8.png
  assets/active-heart.png
  assets/active-home-icon-8.png
  assets/active-lotus-icon-8.png
  assets/calendar-icon-8.png
  assets/calendar-icon_1-8.png
  assets/fav-icon-8.png
  assets/heart.png
  assets/home-icon-8.png
  assets/lotus-icon-8.png
  components/Navigation/CheckListModal.js
Labels: UI/UX

#51 adding navigation to app.js
  App.js
  components/BottomNavBar.js
  components/Carousel/CarouselItem.js
  components/CarouselCards/FavoritesCard.js
  components/Home.js
  components/Navigation/GoodVibeModal.js
  package-lock.json
  package.json
  utilities/data.js
Labels: Class-Component, Data, fetch api, Navigation, MVP

#52 So/feature/modal attempt
  App.js
  components/CarouselCards/FavoritesCard.js
  components/Home.js
Labels: Navigation

#54 Cg/fav/rendering
  App.js
  FavoritesCard.js
  components/Carousel/CarouselItem.js
  components/CarouselCards/FavoritesCard.js
  components/GreetingButton.js
  components/Home.js
  components/Navigation/GoodVibeModal.js
  components/Navigation/StackNavigator.js
Labels: help wanted

#55 Cg/refactor styling
  App.js
  apiCalls.js
  components/BottomNavBar.js
  components/Carousel/CarouselItem.js
  components/Carousel/CustomSlider.js
  components/Carousel/styles.js
  components/CarouselCards/CalendarCard.js
  components/CarouselCards/CheckListCard.js
  components/CarouselCards/FavoritesCard.js
  components/CarouselCards/GoodVibeCard.js
  components/GreetingButton.js
  components/Header.js
  components/Home.js
  components/ModalTemplate.js
  components/Navigation/CalendarModal.js
  components/Navigation/CheckListModal.js
  components/Navigation/FavoritesModal.js
  components/Navigation/GoodVibeModal.js
  components/Navigation/StackNavigator.js
  components/mantraInterval.js
Labels: enhancement, styling, high-priority, UI/UX, Accessibility, Class-Component, Data, fetch api, Navigation, Modal, MVP

#56 Mc/update readme
  README.md
Labels: documentation
